### ISSUE TITLE
Error when the buttons of the tables are generated

### ISSUE THREAD

**Issue by juanlll** [InfyOmLabs/coreui-generator#1]
Hello, find an error when the file of each table is generated: "datatables_actions.blade.php".

A quote is missing at the end of the class attribute of the tag- so ->

>  

`<a class='btn btn-ghost-success> </a>`

**The solution is just to close the attribute with a quote.**

`<a class='btn btn-ghost-success'> </a>`

**Comment by ShaileshInfyom** [comment]
https://github.com/InfyOmLabs/coreui-templates/pull/13

**Comment by mitulgolakiya** [comment]
@juanlll fixed. thanks for catching the issue.
