### ISSUE TITLE
Failed to load resource icons@1.0.1

### ISSUE THREAD

**Issue by matiasdiaz21** [InfyOmLabs/coreui-generator#15]
GET https://unpkg.com/@coreui/icons@1.0.1/css/coreui-icons.min.css net::ERR_ABORTED 404

**Comment by japc-74** [comment]
Hello guys, did you catch this?

**Comment by mitulgolakiya** [comment]
Duplicate https://github.com/InfyOmLabs/coreui-templates/issues/29#issuecomment-589449380

**Comment by ajayinfyom** [comment]
Updated CDN of coreui  icons
